os: osx
osx_image: xcode10
sudo: false
language: objective-c

env:
  - SDK="iphoneos12.0"

script:
  - xcodebuild -project KUIPopOver.xcodeproj clean build -sdk $SDK -configuration Debug CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO

before_install:
  - xcodebuild -showsdks
